### ISSUE TITLE
Ошибка при постинге: JS-Field "post_hash" not found! 

### ISSUE THREAD

**Issue by msgrand** [saippuakauppias/vk-wallposter#1]
Пример:
http://адрес_сайта/weather/vk_post.php

**Comment by saippuakauppias** [comment]
Попробуйте заменить в файле

<pre>classes/vk_poster.class.php</pre>

230 строку следующим:

<pre>
                preg_match('#Location\: ([^\r\n]+)#is', $result, $match);
                if (isset($match[1]) AND !empty($match[1]))
                {
                        $result = $this->minicurl->get_file($match[1]);
                        unset($match);
                        preg_match('#Location\: ([^\r\n]+)#is', $result, $match);
                        if (isset($match[1]) AND !empty($match[1]))
                        {
                                $result = $this->minicurl->get_file($match[1]);
                                unset($match);
                        }
                }
</pre>

**Comment by msgrand** [comment]
http://адрес_сайта/weather/vk_post.php уже поинтереснее, но профита всё нет..

**Comment by saippuakauppias** [comment]
Без ошибок скопировали? там на 230 строке появился символ "<" из-за которого возникает ошибка. У меня такого нету :)

**Comment by msgrand** [comment]
действительно была ошибка при копировании. вот это рез-т при правилном копипасте:
Notice: iconv() [function.iconv]: Detected an illegal character in input string in /home/marat128/public_html/weather/classes/parsing_gismeteo.class.php on line 75

Notice: iconv() [function.iconv]: Detected an illegal character in input string in /home/marat128/public_html/weather/classes/parsing_gismeteo.class.php on line 75

Notice: iconv() [function.iconv]: Detected an illegal character in input string in /home/marat128/public_html/weather/classes/parsing_gismeteo.class.php on line 75

cURL error (3): malformed
Error!
[2011.09.11 22:21:32]: JS-Field "post_hash" not found!

**Comment by saippuakauppias** [comment]
Чем дальше - тем интереснее :)
На каком хостинге используйте? Если на платном, то скиньте мне результат работы phpinfo(). Делается так:
1. Создаётся файлик с форматом .php, например - info.php
2. Открывайте его и вставляйте туда содержимое вот отсюда (тут не получилось опубликовать) https://gist.github.com/1209967
3. Запускайте его и результат скидывайте сюда в прикреплённом файле. Или можете так же написать ссылку.

**Comment by msgrand** [comment]
<?php

// Показать всю информацию, по умолчанию INFO_ALL
phpinfo();

// Показать только информацию модуля.
// phpinfo(8) даст идентичный результат.
phpinfo(INFO_MODULES);

?>
вставил вот это, получил вот это:

Предупреждение : phpinfo () был отключен по соображениям безопасности в / home/marat128/public_html/info.php на линии 4 

Предупреждение : phpinfo () был отключен по соображениям безопасности в / home/marat128/public_html/info.php на линии 8
p.s хостинг платный, iphoster

**Comment by msgrand** [comment]
нельзя никуда повесить эти пару файлов с моими данными ну чтоб 100% работало?

**Comment by saippuakauppias** [comment]
странно что на этом хостинге даже phpinfo() выключен! очень странно! нет никакого другого, чтобы запустить скрипт? А то я пока что-то не вижу решения для этой странной ошибки (cURL error (3): malformed)
