### ISSUE TITLE
переход на vk.com

### ISSUE THREAD

**Issue by lespavl** [saippuakauppias/vk-wallposter#3]
привет
вот уже почти неделя, как контакт переехал и скрипт перестал работать.
я попробовала поменять все vkontakte.ru на vk.com, но это не помогло
вот ошибка, которая заносится в логфайл:

JS-Field "post_hash" not found!

возникает она где-то в функции get_hash
а точнее, 
вот на этом этапе:

preg_match("#act: '([^']+)', code: ge('code').value, to: '([^']+)', al_page: '([^']+)', hash: '([^']+)'#is", $result, $match);
            $post = array(
                'act' => $match[1],
                'al' => '1', // хз что это
                'al_page' => $match[3],
                'code' => $this->phone,
                'hash' => $match[4],
                'to' => $match[2]
            );

му получаем пустой массив

что делать???

**Comment by saippuakauppias** [comment]
Печально...
Надо править скрипт, что-то не получается ему из регулярки данные получить, наверное.

У меня так в ближайшую неделю не будет времени на скрипт, а потом я и забыть могу... Если есть возможность - исправьте, пожалуйста, и пришлите изменения - я исправлю, чтоб другие люди могли пользоваться.

**Comment by lespavl** [comment]
я видела, что вы поправили
но не полностью:
http://ipic.su/img/img3/fs/kiss_44kb.1329380433.jpg

**Comment by saippuakauppias** [comment]
Что-то не так вот с этой регуляркой: https://github.com/saippuakauppias/vk-wallposter/blob/master/classes/vk_poster.class.php#L252
Если исправите - буду благодарен, сейчас пока нет времени на проверку и тестирование :(

**Comment by saippuakauppias** [comment]
Исправлено следующим коммитом: https://github.com/saippuakauppias/vk-wallposter/commit/dda08c3d37b7541e65d5b490e38e396e851d5d2f
