### ISSUE TITLE
Недочеты в preg_match

### ISSUE THREAD

**Issue by okachanov** [saippuakauppias/vk-wallposter#4]
В момент подтверждения телефонного номера не всегда срабатывает регекспа, поскольку al_page может быть пустой. Поэтому паттерн в строке 254:
# act: '([^']+)', code: ge('code').value, to: '([^']+)', al_page: '([^']+)', hash: '([^']+)'#is

стоит заменить на
# act: '([^']+)', code: ge('code').value, to: '([^']+)', al_page: '([^']*)', hash: '([^']+)'#i

**Comment by saippuakauppias** [comment]
Отправьте, пожалуйста, pull request, я приму. Согласен, что этого тут не учёл.

**Comment by okachanov** [comment]
Сделал.

**Comment by saippuakauppias** [comment]
Спасибо!
